[package]
name = "vpnget"
version = "0.1.0"
authors = ["boris"]
edition = "2018"

[dependencies]
reqwest = "0.9.18"
serde = "1.0.92"
serde_json = "1.0.39"
tempfile = "3.0.8"
zip = "0.5.2"
clap = "2.33.0"
ctrlc = "3.1.3"
crossbeam = "0.7.1"
rand = "0.7.0"
